name: novacorp
services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
    restart: unless-stopped
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
